CREATE TABLE IF NOT EXISTS submissions
(
    id                      VARCHAR(255) NOT NULL,
    archived                BOOLEAN,
    author                  VARCHAR(255),
    author_created_utc      BIGINT,
    author_fullname         VARCHAR(255),
    created_utc             BIGINT,
    downs                   INT,
    is_self                 BOOLEAN,
    locked                  BOOLEAN,
    name                    VARCHAR(255),
    num_comments            INT,
    num_crossposts          INT,
    num_reports             INT,
    permalink               TEXT,
    score                   INT,
    selftext                TEXT,
    spoiler                 BOOLEAN,
    subreddit               VARCHAR(255),
    subreddit_id            VARCHAR(255),
    subreddit_name_prefixed VARCHAR(255),
    subreddit_subscribers   INT,
    subreddit_type          VARCHAR(255),
    title                   TEXT,
    total_awards_received   INT,
    ups                     INT,
    upvote_ratio            FLOAT,
    url                     TEXT
);